// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://radokkkfpgvdnfenjixj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZG9ra2tmcGd2ZG5mZW5qaXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1MTc2NzcsImV4cCI6MjA5MTA5MzY3N30.ceH7GRp9nog6hOwKDjU2UAYQ-tRF9IumkpRX-d8CDK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);