// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xleljhiyuhtvzjlxzawy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZWxqaGl5dWh0dnpqbHh6YXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNDk5MTksImV4cCI6MjA4MjYyNTkxOX0.u0lTjYZZl1w8CRAmDXwjEB4qm9clZu_qnBbd6hbFR-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);